### ISSUE TITLE
Ruby Packages Required

### ISSUE THREAD

**Issue by lehitoskin** [lojban/cll#173]
Trying to build in Gentoo it gives the error

```
/usr/lib64/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- trollop (LoadError)
    from /usr/lib64/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from scripts/generate_glossary.rb:4:in `<main>'
Glossary generation failed.
scripts/Makefile:31: recipe for target '/home/lehi/Downloads/cll/build/cll.xml' failed
```

It seems there are several Ruby packages required:
- trollop
- nokogiri (which seems to have its own dependencies)
- htmlentities

Please add these as build dependencies.

After installing these packages, it starts to download jbovlaste.xml, but after a while it fails without giving any more hints on what I can do to fix it.

**Comment by rlpowell** [comment]
On Fri, Sep 25, 2015 at 04:07:27PM -0700, Lehi Toskin wrote:

> Trying to build in Gentoo it gives the error
> 
> ```
> /usr/lib64/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- trollop (LoadError)
>   from /usr/lib64/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>   from scripts/generate_glossary.rb:4:in `<main>'
> Glossary generation failed.
> scripts/Makefile:31: recipe for target '/home/lehi/Downloads/cll/build/cll.xml' failed
> ```
> 
> It seems there are several Ruby packages required:
> - trollop
> - nokogiri (which seems to have its own dependencies)
> - htmlentities
> 
> Please add these as build dependencies.

They are all in the Gemfile; if that isn't what you meant by "build
dependencies", please explain?

> After installing these packages, it starts to download
> jbovlaste.xml, but after a while it fails without giving any more
> hints on what I can do to fix it.

Show me the complete output, please.

**Comment by lehitoskin** [comment]
What I mean is, list this somewhere in the README as, like, "Build dependencies", so people can install them before running into errors. Also, the Gemfile's latest commit message is "Not actually used, really.", which seems rather suspicious. I'm not ruby-savvy, so I have no idea what a Gemfile is or does or why I should look at the contents when the instructions make no mention of it.

Anyway, here is the complete output:

```
> ./cll_build
chapters: chapters/01.xml chapters/02.xml chapters/03.xml chapters/04.xml chapters/05.xml chapters/06.xml chapters/07.xml chapters/08.xml chapters/09.xml chapters/10.xml chapters/11.xml chapters/12.xml chapters/13.xml chapters/14.xml chapters/15.xml chapters/16.xml chapters/17.xml chapters/18.xml chapters/19.xml chapters/20.xml chapters/21.xml 
optlist: 
target: all

Chapter list differences found; forcing a re-merge.

mkdir -p /home/lehi/Downloads/cll/build
rm -f /home/lehi/Downloads/cll/build/xml /home/lehi/Downloads/cll/build/dtd
ln -sf /home/lehi/Downloads/cll/xml /home/lehi/Downloads/cll/build/xml
ln -sf /home/lehi/Downloads/cll/dtd /home/lehi/Downloads/cll/build/dtd
scripts/merge.sh -b "/home/lehi/Downloads/cll/build"  chapters/01.xml chapters/02.xml chapters/03.xml chapters/04.xml chapters/05.xml chapters/06.xml chapters/07.xml chapters/08.xml chapters/09.xml chapters/10.xml chapters/11.xml chapters/12.xml chapters/13.xml chapters/14.xml chapters/15.xml chapters/16.xml chapters/17.xml chapters/18.xml chapters/19.xml chapters/20.xml chapters/21.xml 
Arg Leftovers: chapters/01.xml chapters/02.xml chapters/03.xml chapters/04.xml chapters/05.xml chapters/06.xml chapters/07.xml chapters/08.xml chapters/09.xml chapters/10.xml chapters/11.xml chapters/12.xml chapters/13.xml chapters/14.xml chapters/15.xml chapters/16.xml chapters/17.xml chapters/18.xml chapters/19.xml chapters/20.xml chapters/21.xml
jbovlaste file is old; refetching.
--2015-09-26 00:29:30--  http://jbovlaste.lojban.org/export/xml-export.html?lang=en&bot_key=z2BsnKYJhAB0VNsl
Resolving jbovlaste.lojban.org... 173.13.139.235
Connecting to jbovlaste.lojban.org|173.13.139.235|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/xml]
Saving to: ‘/home/lehi/Downloads/cll/build/jbovlaste.xml’

/home/lehi/Downloads/cll/build/j     [                                      <=>                    ]   9.51M   271KB/s   in 32s    

2015-09-26 00:30:04 (303 KB/s) - ‘/home/lehi/Downloads/cll/build/jbovlaste.xml’ saved [9973173]


NO JBOVLASTE DEFINITION FOR "bisycla" FOUND!
NO JBOVLASTE DEFINITION FOR "calkyguzme" FOUND!
NO JBOVLASTE DEFINITION FOR "cinctu" FOUND!
NO JBOVLASTE DEFINITION FOR "cmacrnintegrale" FOUND!
NO JBOVLASTE DEFINITION FOR "cmacrntegrale" FOUND!
NO JBOVLASTE DEFINITION FOR "dinjrnintegrale" FOUND!
NO JBOVLASTE DEFINITION FOR "fetsygau" FOUND!
NO JBOVLASTE DEFINITION FOR "ge'urzdani" FOUND!
NO JBOVLASTE DEFINITION FOR "ge'uzda" FOUND!
NO JBOVLASTE DEFINITION FOR "gerkyzda" FOUND!
NO JBOVLASTE DEFINITION FOR "gerkyzdani" FOUND!
NO JBOVLASTE DEFINITION FOR "gerselzda" FOUND!
NO JBOVLASTE DEFINITION FOR "gerzdani" FOUND!
NO JBOVLASTE DEFINITION FOR "gicmu" FOUND!
NO JBOVLASTE DEFINITION FOR "gripau" FOUND!
NO JBOVLASTE DEFINITION FOR "grutrceraso" FOUND!
NO JBOVLASTE DEFINITION FOR "integrale" FOUND!
NO JBOVLASTE DEFINITION FOR "klamau" FOUND!
NO JBOVLASTE DEFINITION FOR "labmau" FOUND!
NO JBOVLASTE DEFINITION FOR "lamgri" FOUND!
NO JBOVLASTE DEFINITION FOR "lange'u" FOUND!
NO JBOVLASTE DEFINITION FOR "likygau" FOUND!
NO JBOVLASTE DEFINITION FOR "likyri'a" FOUND!
NO JBOVLASTE DEFINITION FOR "livgyterbilma" FOUND!
NO JBOVLASTE DEFINITION FOR "lo'ikle" FOUND!
NO JBOVLASTE DEFINITION FOR "lo'irlei" FOUND!
NO JBOVLASTE DEFINITION FOR "lojbangri" FOUND!
NO JBOVLASTE DEFINITION FOR "lotkle" FOUND!
NO JBOVLASTE DEFINITION FOR "lotlei" FOUND!
NO JBOVLASTE DEFINITION FOR "mampa'u" FOUND!
NO JBOVLASTE DEFINITION FOR "manskapi" FOUND!
NO JBOVLASTE DEFINITION FOR "mi'erxanpli" FOUND!
NO JBOVLASTE DEFINITION FOR "minkemxanpli" FOUND!
NO JBOVLASTE DEFINITION FOR "mudysiclu" FOUND!
NO JBOVLASTE DEFINITION FOR "nalbrablo" FOUND!
NO JBOVLASTE DEFINITION FOR "nalmle" FOUND!
NO JBOVLASTE DEFINITION FOR "nelcymau" FOUND!
NO JBOVLASTE DEFINITION FOR "nilkla" FOUND!
NO JBOVLASTE DEFINITION FOR "normle" FOUND!
NO JBOVLASTE DEFINITION FOR "nunctikezgau" FOUND!
NO JBOVLASTE DEFINITION FOR "nunji'a" FOUND!
NO JBOVLASTE DEFINITION FOR "nunkalte" FOUND!
NO JBOVLASTE DEFINITION FOR "nunkilbra" FOUND!
NO JBOVLASTE DEFINITION FOR "nunklama" FOUND!
NO JBOVLASTE DEFINITION FOR "nunpinxe" FOUND!
NO JBOVLASTE DEFINITION FOR "nunsoidji" FOUND!
NO JBOVLASTE DEFINITION FOR "nunte'a" FOUND!
NO JBOVLASTE DEFINITION FOR "nunterji'a" FOUND!
NO JBOVLASTE DEFINITION FOR "pacraistu" FOUND!
NO JBOVLASTE DEFINITION FOR "pevrisnyjelca" FOUND!
NO JBOVLASTE DEFINITION FOR "posydji" FOUND!
NO JBOVLASTE DEFINITION FOR "rairgugde" FOUND!
NO JBOVLASTE DEFINITION FOR "ricrxaceru" FOUND!
NO JBOVLASTE DEFINITION FOR "risnyjelca" FOUND!
NO JBOVLASTE DEFINITION FOR "ro'inre'o" FOUND!
NO JBOVLASTE DEFINITION FOR "rokre'o" FOUND!
NO JBOVLASTE DEFINITION FOR "saktrxaceru" FOUND!
NO JBOVLASTE DEFINITION FOR "seldzukla" FOUND!
NO JBOVLASTE DEFINITION FOR "selgekmau" FOUND!
NO JBOVLASTE DEFINITION FOR "seljdasku" FOUND!
NO JBOVLASTE DEFINITION FOR "selkanla" FOUND!
NO JBOVLASTE DEFINITION FOR "selkemdzukla" FOUND!
NO JBOVLASTE DEFINITION FOR "selklamau" FOUND!
NO JBOVLASTE DEFINITION FOR "selnelcymau" FOUND!
NO JBOVLASTE DEFINITION FOR "selselgekmau" FOUND!
NO JBOVLASTE DEFINITION FOR "selseljdasku" FOUND!
NO JBOVLASTE DEFINITION FOR "selzda" FOUND!
NO JBOVLASTE DEFINITION FOR "sikcurnu" FOUND!
NO JBOVLASTE DEFINITION FOR "soidji" FOUND!
NO JBOVLASTE DEFINITION FOR "spatrkoka" FOUND!
NO JBOVLASTE DEFINITION FOR "spraile" FOUND!
NO JBOVLASTE DEFINITION FOR "tarmrnintegrale" FOUND!
NO JBOVLASTE DEFINITION FOR "terci'e" FOUND!
NO JBOVLASTE DEFINITION FOR "tergusni" FOUND!
NO JBOVLASTE DEFINITION FOR "terkakpa" FOUND!
NO JBOVLASTE DEFINITION FOR "terklamau" FOUND!
NO JBOVLASTE DEFINITION FOR "terlantroge'u" FOUND!
NO JBOVLASTE DEFINITION FOR "ti'ifla" FOUND!
NO JBOVLASTE DEFINITION FOR "tricrxaceru" FOUND!
NO JBOVLASTE DEFINITION FOR "turdu'i" FOUND!
NO JBOVLASTE DEFINITION FOR "velmikce" FOUND!
NO JBOVLASTE DEFINITION FOR "xancypliminde" FOUND!
NO JBOVLASTE DEFINITION FOR "xanmi'e" FOUND!
NO JBOVLASTE DEFINITION FOR "xanplimi'e" FOUND!
NO JBOVLASTE DEFINITION FOR "xaskemcakcurnu" FOUND!
NO JBOVLASTE DEFINITION FOR "xasycakcurnu" FOUND!
NO JBOVLASTE DEFINITION FOR "xelklama" FOUND!
NO JBOVLASTE DEFINITION FOR "zilpavypinxe" FOUND!
NO JBOVLASTE DEFINITION FOR "zilrelselpinxe" FOUND!
NO JBOVLASTE DEFINITION FOR "zuljamfu" FOUND!
NO JBOVLASTE DEFINITION FOR "zunlyjamfu" FOUND!
NO JBOVLASTE DEFINITION FOR "zunlyjma" FOUND!
ruby scripts/xml_preprocess.rb /home/lehi/Downloads/cll/build/cll.xml >/home/lehi/Downloads/cll/build/cll_processed_xhtml.xml 2>/tmp/xml_preprocess.out
scripts/Makefile:37: recipe for target '/home/lehi/Downloads/cll/build/cll_processed_xhtml.xml' failed
make: *** [/home/lehi/Downloads/cll/build/cll_processed_xhtml.xml] Error 1
```

**Comment by rlpowell** [comment]
On Sat, Sep 26, 2015 at 12:34:42AM -0700, Lehi Toskin wrote:

> What I mean is, list this somewhere in the README as, like, "Build
> dependencies", so people can install them before running into
> errors.

Ah, OK.  It actually _is_ in the README, it's just that the README
is ludicrously out of date.  I've just updated it.

> Also, the Gemfile's latest commit message is "Not actually
> used, really.", which seems rather suspicious.

That was referring to a package I commented out, not to the file as
a whole.

> I'm not ruby-savvy, so I have no idea what a Gemfile is or does or
> why I should look at the contents when the instructions make no
> mention of it.

_nod_

> Anyway, here is the complete output:
> [snip]
> NO JBOVLASTE DEFINITION FOR "zunlyjma" FOUND!
> ruby scripts/xml_preprocess.rb /home/lehi/Downloads/cll/build/cll.xml >/home/lehi/Downloads/cll/build/cll_processed_xhtml.xml 2>/tmp/xml_preprocess.out
> scripts/Makefile:37: recipe for target '/home/lehi/Downloads/cll/build/cll_processed_xhtml.xml' failed
> make: **\* [/home/lehi/Downloads/cll/build/cll_processed_xhtml.xml] Error 1
> 
> ```
> ```

I need the last bits of /tmp/xml_preprocess.out , but actually it'll
probably work if you just grab the very latest; I fixed a bug a few
hours ago.

**Comment by lehitoskin** [comment]
```
/tmp> cat xml_preprocess.out
/usr/lib64/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- byebug (LoadError)
    from /usr/lib64/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from scripts/xml_preprocess.rb:3:in `<main>'
```

Looks like I need byebug, too?

I just pulled from master and it's starting to build now.

**Comment by rlpowell** [comment]
Re-pull; the latest version no longer requires that.

You are on the docbook-prince branche, yes?

rlpowell@vrici> a byebug
Gemfile
8:# gem 'byebug'

scripts/xml_preprocess.rb
3:# require 'byebug'
rlpowell@vrici>

**Comment by lehitoskin** [comment]
Running it now, it comes with an error.

```
find /home/lehi/Downloads/cll/build/xhtml-nochunks | xargs grep -l '<html xmlns=' | xargs sed -i 's;<html xmlns=;<html xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns=;'
grep: /home/lehi/Downloads/cll/build/xhtml-nochunks: Is a directory
cp /home/lehi/Downloads/cll/scripts/master.css /home/lehi/Downloads/cll/build/xhtml-nochunks/final.css
mv /home/lehi/Downloads/cll/build/xhtml-nochunks/cll_processed_xhtml.html /home/lehi/Downloads/cll/build/xhtml-nochunks/index.html
cp -pr /home/lehi/Downloads/cll/media /home/lehi/Downloads/cll/build/xhtml-nochunks/
touch /home/lehi/Downloads/cll/build/xhtml-nochunks.done
rm -rf ~/public_html/media/public/cll_build/cll-xhtml-nochunks/
mkdir -p ~/public_html/media/public/cll_build/cll-xhtml-nochunks/
cp /home/lehi/Downloads/cll/build/xhtml-nochunks ~/public_html/media/public/cll_build/cll-xhtml-nochunks
cp: omitting directory ‘/home/lehi/Downloads/cll/build/xhtml-nochunks’
scripts/Makefile:77: recipe for target 'xhtml_nochunks_web' failed
make: *** [xhtml_nochunks_web] Error 1
```

Looks like it's trying to operate on a directory when it's expecting a file.

**Comment by rlpowell** [comment]
This: cp /home/lehi/Downloads/cll/build/xhtml-nochunks ~/public_html/media/public/cll_build/cll-xhtml-nochunks<F29>
1.  If you don't have such a directory setup, run -T xhtml_nochunks instead of xhtml_nochunks_web
2.  There's a bug there, sorry; re-pull

**Comment by lehitoskin** [comment]
Running it now, it comes with an error.
```
find /home/lehi/Downloads/cll/build/xhtml-nochunks | xargs grep -l '<html xmlns=' | xargs sed -i 's;<html xmlns=;<html xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns=;'
grep: /home/lehi/Downloads/cll/build/xhtml-nochunks: Is a directory
cp /home/lehi/Downloads/cll/scripts/master.css /home/lehi/Downloads/cll/build/xhtml-nochunks/final.css
mv /home/lehi/Downloads/cll/build/xhtml-nochunks/cll_processed_xhtml.html /home/lehi/Downloads/cll/build/xhtml-nochunks/index.html
cp -pr /home/lehi/Downloads/cll/media /home/lehi/Downloads/cll/build/xhtml-nochunks/
touch /home/lehi/Downloads/cll/build/xhtml-nochunks.done
rm -rf ~/public_html/media/public/cll_build/cll-xhtml-nochunks/
mkdir -p ~/public_html/media/public/cll_build/cll-xhtml-nochunks/
cp /home/lehi/Downloads/cll/build/xhtml-nochunks ~/public_html/media/public/cll_build/cll-xhtml-nochunks
cp: omitting directory ‘/home/lehi/Downloads/cll/build/xhtml-nochunks’
scripts/Makefile:77: recipe for target 'xhtml_nochunks_web' failed
make: *** [xhtml_nochunks_web] Error 1
```

Looks like it's trying to operate on a directory when it's expecting a file.

**Comment by rlpowell** [comment]
Is it working now?

**Comment by lehitoskin** [comment]
Testing now, it'll take a while to build.

**Comment by lehitoskin** [comment]
I've run into this error now:

```
ruby scripts/xml_prince_postprocess.rb /home/lehi/Downloads/cll/build/prince_pdf/cll_processed_xhtml.html >/home/lehi/Downloads/cll/build/prince_pdf/cll_processed_xhtml_prince.html 2>/tmp/xml_prince_postprocess.out
prince -vvv --script=scripts/prince_check_margins.js /home/lehi/Downloads/cll/build/prince_pdf/cll_processed_xhtml_prince.html /home/lehi/Downloads/cll/build/cll_prince.pdf
make: prince: Command not found
scripts/Makefile:125: recipe for target '/home/lehi/Downloads/cll/build/prince_pdf.done' failed
make: *** [/home/lehi/Downloads/cll/build/prince_pdf.done] Error 127
```

This was done by running `./cll_build` without any flags, but running with `-T xhtml_pages` allows it to build to completion.

P.S. Looks like the reason it failed is because I don't have prince installed. And looking at the license for prince, I don't believe I'll be doing so. In any case, thanks are building now so thank you for your hard work!

**Comment by rlpowell** [comment]
Yes, you need to have prince installed; the new README says that.  http://www.princexml.com/download/

On the plus side, that's the last step for the PDF, pretty much, so
you should be home free after that.

**Comment by rlpowell** [comment]
\o/
